config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => {:omniauth_callbacks => "devise/omniauth_callbacks"}
  resources :users, :posts
  root 'home#index'

  resources :tokens,:only => [:create], defaults: {format: 'json'}
  post 'tokens/get_key' => 'tokens#get_key', defaults: {format: 'json'}
  post 'tokens/user_sign_up' => 'tokens#user_sign_up', defaults: {format: 'json'}
  get 'tokens/destroy_token' => 'tokens#destroy_token', defaults: {format: 'json'}
  get 'tokens/check_token' => 'tokens#check_token', defaults: {format: 'json'}
  post 'tokens/facebook_authentication' => 'tokens#facebook_authentication', defaults: {format: 'json'}
  
  # get '*path' => redirect('/')
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  attr_accessor :image
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :omniauthable#, :confirmable

  has_many :pictures, as: :pictureable, dependent: :destroy
  has_many :posts, dependent: :destroy
  has_many :access_tokens, dependent: :destroy
  before_create :ensure_authentication_token, :generate_key
  validates_presence_of :email, :message => "Please enter email"
  
  # accepts_nested_attributes_for :pictures, reject_if: :image_blank, :allow_destroy => true

  def self.from_facebook_omniauth(auth)
    email = auth.info.email.present? ? auth.info.email : "#{auth.uid}@facebook.com"
    user_exist = User.find_by_email(email)
    if user_exist.nil?
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = email
        user.first_name = auth.info.name.split(' ')[0]
        user.last_name = auth.info.name.split(' ')[1]
        user.user_name = auth.info.name.split(' ')[0].downcase
        user.password = Devise.friendly_token[0,20]
      end
    else
      user_exist.update(provider: auth.provider, access_token: auth.credentials.token, uid: auth.uid, first_name: auth.info.name, last_name: nil)
    end
    user_exist = User.find_by_email(email)
  end

  def self.full_name(user_id)
    first_name = User.find(user_id).first_name rescue nil
    last_name = User.find(user_id).last_name rescue nil
    return first_name + ' ' +last_name
  end

  def generate_key
    self.key = Digest::SHA1.hexdigest(BCrypt::Engine.generate_salt)
  end

  def ensure_authentication_token
    token = self.authentication_token = self.generate_authentication_token
  end

  def generate_authentication_token
    token = Devise.friendly_token
    access = AccessToken.find_or_create_by(token: token, user_id: self.id)
    access
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	# skip_before_action :authenticate_user!
	before_filter :authenticate_user!
	def show
		@user = current_user
	end

	def edit
		@user = current_user
	end

	def update
		@user = current_user
		binding.pry
		if @user.update_attributes(user_params)
			Picture.create(:picturable_id=>current_user.id,:picturable_type=>params[:picturable_type],:image=>params[:image])
			redirect_to user_path(@user.id)
		else
			render :action => 'edit'
		end
	end

	protected

	def user_params
		params.require(:user).permit!
	end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.haml
= form_for (@user), :html => { :multipart => true } do |f|
  .field
    = f.label :image, "Profile Picture"
    %br/
    =# file_field_tag :image, autofocus: true
    = file_field_tag 'image', :accept => 'image/jpeg', :multiple => true
  .field
    = f.label :first_name, "First Name"
    %br/
    = f.text_field :first_name
  .field
    = f.label :last_name, "Last Name"
    %br/
    = f.text_field :last_name, autofocus: true
  .field
    = f.label :user_name, "User Name"
    %br/
    = f.text_field :user_name, autofocus: true
  .field
    = f.label :email, "Email Id"
    %br/
    = f.email_field :email, autofocus: true
    = hidden_field_tag :picturable_type, "User"
  = f.submit "save"

app/views/users/edit.html.haml
= render :partial => 'form'

app/views/users/show.html.haml
%table
  %tr
    %th
      First Name
    %th
      Last Name
    %th
      User Name
    %th
      Email Id
  %tr
    %td.font16
      = @user.first_name
    %td.font16
      = @user.last_name
    %td.font16
      = @user.user_name
    %td.font16
      = @user.email
    %td.font16
      = link_to "Edit", edit_user_path(current_user.id)
      = link_to "Create Post", new_post_path
      = link_to "All Posts", posts_path